export const config = {
  SIGNAL_COOLDOWN: 5 * 60 * 1000,
  MIN_SIGNAL_SCORE: 6,
  MAX_ACTIVE_SIGNALS: 10,
  DEAD_MARKET_VOLUME_RATIO: 1.2,
  DEAD_MARKET_OI_CHANGE: 0.5,
  ORDERBOOK_DEPTH: 20,
  LIQUIDATION_KEEP: 100,
  TRADE_HISTORY_KEEP: 500,
  RISK_PERCENT: 2,
  STOP_LOSS_PERCENT: 2,
  TP_MULTIPLIERS: [1, 2, 3],
  WEIGHTS: {
    oi: 2,
    volume: 2,
    flow: 2,
    momentum: 1
  }
};

export const STAGES = {
  IDLE: 'IDLE',
  PRESSURE: 'PRESSURE',
  BREAKOUT: 'BREAKOUT',
  SNIPER: 'SNIPER'
};
